### ISSUE TITLE
"Developer" or "person" instead of "engineer"?

### ISSUE THREAD

**Issue by jsmanrique** [mercedes-benz/mercedes-benz-foss-manifesto#11]
As an open source contributor looking for the most inclusive language possible, wouldn't it be more "inclusive" to use a different and more "generic" wording than "engineer" to talk about company's people in the "Employee Principles"?

I was thinking about something like:
"Any person shall look for ..."

What do you think? I could write a PR if we agree ;-)

**Comment by wgehring** [comment]
Hey Manrique,
thanks for the suggestion!
Of course we want to be inclusive. But in this case, we do mean "(software) engineer" / developer, because it is them who write code (in employee principles I-II). Behaving nicely (principle IV) is everybody's responsibility which is why here we wrote "any employee" (because of course there are non-code contributions in Open Source, which is why this doesn't necessarily have to be an engineer/developer).

We regard "Engineer" - meaning "Software Engineer", because we are talking about software development as synonymous to "developer". 

Ok for you?
